namespace: "victorock"
name: "ansible_code"
version: "0.0.1"
readme: "README.md"
authors:
    - "Victorock"
dependencies:
    "kubernetes.core": ">=2.2.0"
license:
    - "GPLv3"
tags:
    - collection
repository: "https://www.github.com/victorock/victorock.ansible_code"