---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: ansible-runner
        image: quay.io/victorock/ansible-code:latest
        command: ["ansible-runner", "run", "/runner"]
        env:
        - name: DEFAULT_RUNNER_ROLE
          value: victorock.apm.setup
          
      restartPolicy: Never
  backoffLimit: 4


  podman run --rm -e RUNNER_PLAYBOOK=test.yml -v $PWD/demo:/runner quay.io/ansible/ansible-runner:latest