---
- name: "Ansible Run"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - include_role:
        name: "victorock.ansible_code.k8s"
      vars:
        k8s_resources_user: "{{ lookup('env', 'ANSIBLE_CODE_USER') | default(ansible_code_user, true) }}"
        k8s_secrets_authorized_keys: "{{ lookup('env', 'ANSIBLE_CODE_AUTH_KEYS') | default(ansible_code_authorized_keys, true) }}"
        k8s_secrets_ssh_host_rsa_key: "{{ lookup('env', 'ANSIBLE_CODE_HOST_RSA_KEY') | default(ansible_code_ssh_host_rsa_key, true )}}"

